### ISSUE TITLE
@types/belvo outdate

### ISSUE THREAD

**Issue by fermedinav** [belvo-finance/belvo-js#118]
The lib @types/belvo 0.16.2 is outdate.

- `created_at` field is missed in InvoicesReturn
- Function `this.belvoClient.taxReturns.retrieve` only accept yearFrom and yearTo like a numbers, so I can't call to this function with type `monthly`. In the documentation it is possible:

```js
// check our node package on github
// https://github.com/belvo-finance/belvo-js

var belvo = require('belvo').default;

var client = new belvo(
  'Secret Key ID',
  'Secret Key PASSWORD',
  'sandbox'
);

// Yearly Tax Returns
client.connect()
  .then(function () {
    client.taxReturns.retrieve('linkID', "2019", "2020")
      .then(function (res) {
        console.log(res);
      })
      .catch(function (error) {
        console.log(error);
      });
});

// Monthly Tax Returns

client.connect()
  .then(function () {
    client.taxReturns.retrieve('linkID', "2019-01-01", "2019-04-01", {type: 'monthly'})
      .then(function (res) {
        console.log(res);
      })
      .catch(function (error) {
        console.log(error);
      });
});
```

**Comment by GeoffreyVanderCruyssen** [comment]
Hello, 

`@types/belvo` is an unofficial lib and therefore not maintained by us. If you really want, you can always try over at https://github.com/DefinitelyTyped/DefinitelyTyped to get this resolved.

Kind regards,
Geoffrey

**Comment by fermedinav** [comment]
I haven't used the @types/belvo library in weeks. But thanks

**Comment by benitocas88** [comment]
Hi @fermedinav can you share with us in what environment are you facing those issues? Production, Development or Sandbox.
