### ISSUE TITLE
1 high vulnerability with package

### ISSUE THREAD

**Issue by javiergutzp** [belvo-finance/belvo-js#64]
When updating from version 0.8.0 to version 0.9.0 got a 2 vulnerabilities. On of them with the "high" tag. Related to a axios pachage.  Screenshot attached.

![image](https://user-images.githubusercontent.com/15876184/105087838-b7af2080-5a60-11eb-84c8-5a53c0782038.png)

The low vulnerability idoes not seem like a real issue, but I hink is worth taking a look. Screenshot attached too.

![image](https://user-images.githubusercontent.com/15876184/105088048-fe9d1600-5a60-11eb-9921-a6adfc11a42a.png)

**Comment by AlbertMaristany** [comment]
Hey @javiergutzp thanks for your input! We fixed that in the recent 0.9.1 version.
